version: '3.9'
services:

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=dark
    volumes:
      - ./configs/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    volumes:
      - ./configs/tempo/tempo-local.yaml:/etc/tempo-local.yaml
    command: ["-config.file=/etc/tempo-local.yaml"]

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus.yaml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.113.0
    container_name: otel-collector
    command:
      - --config=/etc/otel-collector-config.yaml
    volumes:
      - ./configs/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  
  api_gateway:
    build:
      context: api-gateway
    image: api_gateway
    container_name: api_gateway
    environment:
      SERVICE_NAME: api_gateway
      SERVICE_INSTANCE_ID: api_gateway
      ENV: dev
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      PRODUCT_INFO_SERVICE_URL: http://product_info_querier:8080
      PRODUCT_PRICE_SERVICE_URL: http://product_price_querier:8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DB: mysql
    ports:
      - "8080:8080"
  
  product_info_querier:
    build:
      context: product-info-querier
    image: product_info_querier
    container_name: product_info_querier
    environment:
      SERVICE_NAME: product-info-querier
      SERVICE_INSTANCE_ID: product-info-querier
      ENV: dev
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      FAULT_INJECTION_ENABLED: "true"
      FAULT_INJECTION_RATE: 35

  product_price_querier:
    build:
      context: product-price-querier
    image: product_price_querier
    container_name: product_price_querier
    environment:
      SERVICE_NAME: product-price-querier
      SERVICE_INSTANCE_ID: product-price-querier
      ENV: dev
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DB: mysql
      DELAY_INJECTION_ENABLED: "true"
      DELAY_INJECTION_RATE: 55
      DELAY_INJECTION_MS: 1200
  
  
