FROM python:3.12-alpine AS base
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

FROM python:3.12-alpine AS runtime
WORKDIR /app
RUN addgroup -S app && adduser -S app -G app
EXPOSE 8080
COPY --from=base /usr/local/lib/python3.12/site-packages/ /usr/local/lib/python3.12/site-packages/
RUN chown -R app:app /app
COPY src/ .
USER app
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]